# Generated by Django 5.0.4 on 2024-05-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observation', models.TextField()),
                ('time', models.TimeField()),
                ('is_active', models.SmallIntegerField(choices=[(0, 'EN PROCESO'), (1, 'PROCESADA'), (2, 'CONFIRMADA'), (3, 'CANCELADA'), (4, 'REPROGRAMADA'), (5, 'FINALIZADA')], default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
